### PR TITLE
listen and unlisten can accept null nodes

### PR DESCRIPTION
**Pull request by rictic**
They're implemented defensively: 
  https://github.com/Polymer/polymer/blob/cb68ce54ebdcfb2d6f7342e801574881fb158076/src/standard/events.html#L88
  https://github.com/Polymer/polymer/blob/cb68ce54ebdcfb2d6f7342e801574881fb158076/src/standard/events.html#L158

### CODE REVIEW

**Comment by jklein24** [comment]
Is undefined also valid then? If so, can you make this {?EventTarget=} to be super explicit? If not, {?EventTarget}.

**Comment by zhaoz** [comment]
You can't do this on listen.

https://github.com/Polymer/polymer/blob/cb68ce54ebdcfb2d6f7342e801574881fb158076/src/standard/events.html#L88

For listen, if the handler isn't found, it tries to create one.

**Comment by rictic** [comment]
Sorry for the slow response, removed changes to unlisten, allow listen to explicitly accept either null or underfined

**Comment by jklein24** [comment]
I think @zhaoz might be right here. Does it really make sense to create a listener on a null or undefined node?

**Comment by rictic** [comment]
Revised commit to only allow unlisten to be null.

I don't think it's worth explicitly allowing undefined.

**Comment by jklein24** [comment]
LGTM

**Pull request merged**
