### PR TITLE
Add missing return type for PolymerElement.prototype.$$

### PR DESCRIPTION
**Pull request by fredj**
https://github.com/Polymer/polymer/blob/master/src/standard/utils.html#L18-L29

### CODE REVIEW

**Comment by jklein24** [comment]
@rictic can you verify that this doesn't break a bunch of existing code in the same way as #42? This one I really think should at least have _some_ return value and documentation so maybe here it's worth fixing existing broken use cases if there aren't a ton.

**Comment by rictic** [comment]
Kicked off a test run

**Comment by rictic** [comment]
Only a few breaks, easy to fix.

Manually verified that fredj's good for the CLA.

LGTM.

**Comment by fredj** [comment]
Thanks

**Pull request merged**
